services:
  dispatch:
    build: .
    container_name: dispatch
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://cache'
      DEVELOPMENT: 'true'
  redis:
    image: redis:7-alpine
    container_name: cache
    volumes:
      - cache:/data

volumes:
  cache:
