version: "3.9"
services:

  dispatch:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    #command: tail -f /dev/null


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"